### ISSUE TITLE
FA from code behind.

### ISSUE THREAD

**Issue by Pinox** [AvantiPoint/AP.MobileToolkit.Fonts#17]
Nice library.
Is there any examples of using fontawesome from code behind ?

**Comment by dansiegel** [comment]
Pretty much like you would in XAML.

https://github.com/AvantiPoint/AP.MobileToolkit.Fonts/blob/574fa7e32d844d0ec4fc6d2bd1efdba7d2722968/sample/SampleFonts/SampleFonts/Mappings.xaml#L9-L11

```cs
public class SomePage : ContentPage
{
    public SomePage()
    {
        IconImageSource = new IconImageSource { Name = FontAwesomeRegular.Map, Size = 32 };
    }
}
```
