### ISSUE TITLE
Mapping icons by codes

### ISSUE THREAD

**Issue by alexeygritsenko** [AvantiPoint/AP.MobileToolkit.Fonts#28]
Hi, I didn't find such a possibility, but it would be great to have an enumeration of icons by codes or a method for converting an icon to a code

now:
public const string Smile = "fas fa-smile";

do this way:
public const string Smile = "\uf118";

or method:
GetIconCode(FontAwesomeSolid.Smile)

**Comment by dansiegel** [comment]
Check the Mappings namespace you'll see a class that contains the value you need. You can see an example in XAML, but the same can be done in Code. Just make sure you bring in the appropriate namespace. You may need to do an alias if using this in Code.

https://github.com/AvantiPoint/AP.MobileToolkit.Fonts/blob/a7bc77378b52833863313f508530e9fee3190195/sample/SampleFonts/SampleFonts/Mappings.xaml#L25

For the sample that gives you the strongly typed equivalent of `far fa-user`
